media: public/assets/img
content:
  - name: home
    label: Home page
    path: content/_index.md
    type: file
    fields:
      - label: 'Slider 1'
        name: 'slider1'
        type: 'object'
        fields:
          - { label: 'Span', name: 'span', type: 'string' }
          - { label: 'Text', name: 'text', type: 'string' }

      - label: 'Slider 2'
        name: 'slider2'
        type: 'object'
        fields:
          - { label: 'Span', name: 'span', type: 'string' }
          - { label: 'Text', name: 'text', type: 'string' }

      - label: 'Slider 3'
        name: 'slider3'
        type: 'object'
        fields:
          - { label: 'Span', name: 'span', type: 'string' }
          - { label: 'Text', name: 'text', type: 'string' }
      
      - label: 'Card 1'
        name: 'card1'
        type: 'object'
        fields:
          - { label: 'Title', name: 'title', type: 'string' }
          - { label: 'Text', name: 'description', type: 'string' }
      
      - label: 'Card 2'
        name: 'card2'
        type: 'object'
        fields:
          - { label: 'Title', name: 'title', type: 'string' }
          - { label: 'Text', name: 'description', type: 'string' }
      
      - label: 'Card 3'
        name: 'card3'
        type: 'object'
        fields:
          - { label: 'Title', name: 'title', type: 'string' }
          - { label: 'Text', name: 'description', type: 'string' }
  
  - name: header
    label: Header
    path: data/header.yml
    type: file
    fields:
      - label: 'Logo alt text'
        name: 'logo_alt'
        type: 'string'

      - label: 'Logo url'
        name: 'logo_url'
        type: 'string'  

      - label: 'Working title'  
        name: 'working_title'
        type: 'string'
      
      - label: 'Navigation'
        name: 'nav'
        type: 'object'
        fields:
          - { label: 'Name', name: 'name', type: 'string' }
          - { label: 'URL', name: 'url', type: 'string' }
      
      - label: 'Social Media'
        name: 'social_media'
        type: 'object'
        fields:
          - { label: 'Name', name: 'name', type: 'string' }
          - { label: 'URL', name: 'url', type: 'string' }