baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Two44 Software Solutions'

[params]
website = 'https://two44software.com/'
experience = '5'
description = 'two44 software solutions'
email = 'info@two44software.com'
mobile = '+91-8897443700'
address = 'Hyderabad'
keywords = 'best digital marketing in hyderabad'